import type { BlindLevel } from "@/lib/timer/types";

export type BlindPresetName = "turbo" | "standard" | "deep";

export const blindPresets: Record<BlindPresetName, Omit<BlindLevel, "id">[]> = {
  turbo: [
    {
      levelOrder: 1,
      smallBlind: 25,
      bigBlind: 50,
      ante: null,
      durationSeconds: 600,
      isBreak: false,
      breakDurationSeconds: null,
    },
    {
      levelOrder: 2,
      smallBlind: 50,
      bigBlind: 100,
      ante: null,
      durationSeconds: 600,
      isBreak: false,
      breakDurationSeconds: null,
    },
    {
      levelOrder: 3,
      smallBlind: 100,
      bigBlind: 200,
      ante: 25,
      durationSeconds: 600,
      isBreak: false,
      breakDurationSeconds: null,
    },
  ],
  standard: [
    {
      levelOrder: 1,
      smallBlind: 25,
      bigBlind: 50,
      ante: null,
      durationSeconds: 1200,
      isBreak: false,
      breakDurationSeconds: null,
    },
    {
      levelOrder: 2,
      smallBlind: 50,
      bigBlind: 100,
      ante: null,
      durationSeconds: 1200,
      isBreak: false,
      breakDurationSeconds: null,
    },
    {
      levelOrder: 3,
      smallBlind: 75,
      bigBlind: 150,
      ante: null,
      durationSeconds: 1200,
      isBreak: false,
      breakDurationSeconds: null,
    },
    {
      levelOrder: 4,
      smallBlind: 100,
      bigBlind: 200,
      ante: 25,
      durationSeconds: 1200,
      isBreak: false,
      breakDurationSeconds: null,
    },
  ],
  deep: [
    {
      levelOrder: 1,
      smallBlind: 25,
      bigBlind: 50,
      ante: null,
      durationSeconds: 1800,
      isBreak: false,
      breakDurationSeconds: null,
    },
    {
      levelOrder: 2,
      smallBlind: 50,
      bigBlind: 100,
      ante: null,
      durationSeconds: 1800,
      isBreak: false,
      breakDurationSeconds: null,
    },
    {
      levelOrder: 3,
      smallBlind: 75,
      bigBlind: 150,
      ante: null,
      durationSeconds: 1800,
      isBreak: false,
      breakDurationSeconds: null,
    },
    {
      levelOrder: 4,
      smallBlind: 100,
      bigBlind: 200,
      ante: 25,
      durationSeconds: 1800,
      isBreak: false,
      breakDurationSeconds: null,
    },
    {
      levelOrder: 5,
      smallBlind: 150,
      bigBlind: 300,
      ante: 25,
      durationSeconds: 1800,
      isBreak: false,
      breakDurationSeconds: null,
    },
  ],
};
