"use server";

import { revalidatePath } from "next/cache";
import { CARD_BATCH_MAX, normalizeCardPrefix } from "@/lib/cards/card-batch";
import { deleteCardBatch, saveCardBatch } from "@/lib/cards/card-batch-store";
import { hasPublicEnv } from "@/lib/env";
import { createSupabaseServerClient } from "@/lib/supabase/server";

/**
 * Writes down a run the admin just generated, so the next one knows where to start.
 *
 * The page saves as it generates rather than behind a button of its own: a run that was
 * printed but never written down is exactly how the club ended up with two MJ-001s.
 */
export async function rememberCardBatch(input: {
  count: number;
  prefix: string;
  startNumber: number;
}) {
  // Without Supabase there is nowhere to write it down; the sheet still prints.
  if (!hasPublicEnv()) return;

  // Stored the way it is printed, so the history and the cards name the same pack.
  const prefix = normalizeCardPrefix(String(input.prefix ?? ""));
  const count = Math.min(CARD_BATCH_MAX, Math.max(1, Math.floor(input.count) || 1));
  const startNumber = Math.max(1, Math.floor(input.startNumber) || 1);

  const supabase = await createSupabaseServerClient();
  await saveCardBatch(supabase, { count, prefix, startNumber });

  revalidatePath("/admin/qr-codes");
}

/** Drops a run that was generated by mistake and never went to the printer. */
export async function forgetCardBatch(id: string) {
  const batchId = String(id ?? "").trim();
  if (!batchId || !hasPublicEnv()) return;

  const supabase = await createSupabaseServerClient();
  await deleteCardBatch(supabase, batchId);

  revalidatePath("/admin/qr-codes");
}
