-- One player, however their nickname was typed.
--
-- The club writes a nickname differently in every sheet — "Kabedev" and "kabedev",
-- "adam_smasher" and "ADAM SMASHER" — and matching on the text itself made one player
-- look like several: their games were split, and an evening imported twice under two
-- spellings counted as two games played.
--
-- The key is everything but letters and digits removed, lower-cased. It is generated by
-- the database so it can never drift from the name it belongs to, and `lib/players/
-- nickname-key.ts` computes the same string for the queries that filter on it.

alter table public.tournament_results
  add column if not exists player_key text
    generated always as (regexp_replace(lower(player_name), '[^a-z0-9а-яё]', '', 'g')) stored;

create index if not exists tournament_results_player_key_idx
  on public.tournament_results (player_key);

alter table public.client_bot_users
  add column if not exists nickname_key text
    generated always as (regexp_replace(lower(display_name), '[^a-z0-9а-яё]', '', 'g')) stored;

create index if not exists client_bot_users_nickname_key_idx
  on public.client_bot_users (nickname_key);
